name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Unit Tests
      run: |
        if [ -f test_all_models.py ]; then python -m unittest test_all_models.py; else echo "Test file not found, skipping tests."; fi

    - name: Lint with pylint
      run: |
        if [ -f app.py ]; then python -m pylint app.py; else echo "app.py not found, skipping lint."; fi
