name: Python Tests

on: [push]  # Runs on every push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Check out your code
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        pip install pytest pylint
        pip install -r requirements.txt  # If you have one
    
    - name: Run tests
      run: |
        python -m unittest tests/test_all_models.py
    
    - name: Lint
      run: |
        pylint app.py
